### ISSUE TITLE
When the "Show Language Dropdown with Field" is enabled, the field busts out of its container

### ISSUE THREAD

**Issue by petehjfd** [nystudio107/craft-code-field#4] opened 2023-01-04 10:37 UTC
### Describe the bug
When the "Show Language Dropdown with Field" is enabled, the field extends beyond the right edge of its container.

In the screenshot below, the first field (Head start) has the language dropdown enabled and the second field ((Head end) does not.  The fields are otherwise identical.

Tested in Firefox and Chrome.

### To reproduce
Steps to reproduce the behaviour:
1. Create a field with the "Show Language Dropdown with Field" setting enabled
2. Add the field to a section, global set, etc (in this case it has been added to a global set but was also tested with a section)
3. See the field extend beyond the right edge of its container

### Expected behaviour
The field should stay within its container

### Screenshots

<img width="920" alt="Screenshot 2023-01-04 at 10 29 54" src="https://user-images.githubusercontent.com/29060670/210536033-f4368bd5-f8e4-42b7-9d3b-0d0081422d05.png">

### Versions
- Plugin version: 4.0.6
- Craft version: 4.3.5

**Comment by khalwat** [comment] 2023-01-05 03:31
I tested this with Craft CMS 4.3.6 & Code Field 4.0.6 and I'm not seeing this issue:

<img width="852" alt="Screenshot 2023-01-04 at 10 29 52 PM" src="https://user-images.githubusercontent.com/7570798/210695683-de77129e-0c02-4e1f-990d-25d1557adbe9.png">

I only tried it on Chrome, but I'm not seeing it overrun the container at any window size...

Could there be another field in the mix or CP CSS or JS or something else that could be affecting things here?

**Comment by petehjfd** [comment] 2023-01-05 09:35
Hmm very odd. I do have CP CSS installed, and that was my first guess, but I tried disabling that and all other plugins and the issue remained.

I can't even work out which CSS property is causing the problem.

The only thing I've been able to establish is that the offending CSS is being applied with JS.  If I disable JS, I get Craft's "JavaScript must be enabled to access the Craft CMS control panel" modal, but beneath that I can see that the element is the correct width.

<img width="812" alt="Screenshot 2023-01-05 at 09 33 44" src="https://user-images.githubusercontent.com/29060670/210747996-220bbbf2-6d94-46f4-92db-4739d71ae7e5.png">

I don't actually need the language dropdown for this site so if you can't replicate the issue, I'd be happy for you to close it.

**Comment by khalwat** [comment] 2023-01-05 15:10
So strange, especially that I can't reproduce it here. If I can reproduce it, I can fix it!

If you inspect the DOM, does anything stand out obviously as causing the issue?

**Comment by khalwat** [comment] 2023-01-05 15:10
Also, try updating to Craft 4.3.6 to make sure we're on the same page?

**Comment by petehjfd** [comment] 2023-01-05 15:43
As far as I can tell...

With JavaScript disabled, the field has the following markup:

```
<textarea id="fields-headStartvalue" class="text fullwidth" name="fields[headStart][value]" rows="2" cols="50" placeholder="" aria-describedby="fields-headStart-instructions"></textarea>
```

and the `fullwidth` class gives the textarea a width of 100%.

With JavaScript enabled, the textarea is obviously replaced with the monaco editor.  The element with class `monaco-editor` has a width applied to it by JavaScript.  So I can't see exactly where that is coming from.

I've updated to Craft 4.3.6 and that had no effect.

Thanks

**Comment by jeremysanchez** [comment] 2023-02-11 06:14
I am seeing the same problem on Craft version 4.3.8.2 using Chrome Version 109.0.5414.119.

<img width="1173" alt="Screenshot 2023-02-10 at 23 12 37" src="https://user-images.githubusercontent.com/493862/218243648-d2ddfefe-04ca-4d16-81f2-8f225b375c43.png">

In my case it also only happens when the "Show Language Dropdown with Field" setting is enabled.

**Comment by khalwat** [comment] 2023-02-11 18:52
Any way to poke around in the DOM via the inspector to see what's causing this?

I wish I could reproduce this locally here, because it'd be easy to fix then... but I can't.

**Comment by khalwat** [comment] 2023-02-15 15:08
If either of you two are willing to do a screen share where I can check out what's going on, that'd be helpful!

https://savvycal.com/nystudio107/chat

**Comment by jeremysanchez** [comment] 2023-02-15 16:05
> If either of you two are willing to do a screen share where I can check out what's going on, that'd be helpful!

I could do a quick screen share this morning. I'll be in the middle of the Mojave desert the rest of the week.

**Comment by khalwat** [comment] 2023-02-15 16:47
@jeremysanchez are you on the Craft Discord? Perhaps you could DM me there to coordinate?

**Comment by khalwat** [comment] 2023-02-15 19:13
This ended up being due to the `min-inline-size` CSS property being set to `min-content` by the user-agent stylesheet.

The reason I couldn't reproduce it is I had one of my plugins installed that changed this CSS styling already (!)

Thanks for your help @jeremysanchez

**Comment by khalwat** [comment] 2023-02-15 19:27
Addressed in: https://github.com/nystudio107/craft-code-field/commit/68e353565f54ac12eae89873a3228f7bcfe062d1 & https://github.com/nystudio107/craft-code-field/commit/3a75b1a192b8f3623a9566f8a21f404f727cff43

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-code-field": "dev-develop as 3.0.7",
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-code-field": "dev-develop-v4 as 4.0.7”,
```
Then do a `composer clear-cache && composer update`

**Closed as completed by khalwat** 2023-02-15 19:27 UTC
Labels: bug

**Comment by khalwat** [comment] 2023-02-15 19:56
Released as:

Craft 3: Version 3.0.7 -> https://github.com/nystudio107/craft-code-field/releases/tag/3.0.7

Craft 4: Version 4.0.7 -> https://github.com/nystudio107/craft-code-field/releases/tag/4.0.7
