### ISSUE TITLE
Revisions don't render code fields. Drafts do

### ISSUE THREAD

**Issue by gbowne-quickbase** [nystudio107/craft-code-field#12] opened 2023-10-04 18:24 UTC
### Describe the bug
When I look at a previous revision of a page that contains a code field, it just shows as a text area. Really a low priority, but wanted to report for clarity. Thanks! 

### To reproduce
1. Create a page with a code field on it. Save it.
2. Make a revision or a draft. Save it and publish it
3. Look back at a previous version in the CP.

### Expected behaviour
The code field would display as code with formatting, instead of a text block. Drafts seem to function just fine

### Screenshots
Current revision: 
<img width="386" alt="image" src="https://github.com/nystudio107/craft-code-field/assets/39066452/19bfb55b-e962-42c6-a837-d5319f69ce81">
Previous Revision:
<img width="891" alt="image" src="https://github.com/nystudio107/craft-code-field/assets/39066452/cce48051-71f1-4c15-88e2-7f2a18c2567a">
Draft: 
<img width="479" alt="image" src="https://github.com/nystudio107/craft-code-field/assets/39066452/a7b17ddb-04c5-4006-8715-7f210d3fa787">

### Versions
- Plugin version: 4.0.10
- Craft version: 4.5.6.1

**Comment by khalwat** [comment] 2023-10-05 12:11
So this was pretty interesting... when displaying revisions, the field's `::getStaticHtml()` method is called instead of `::getInputHtml()`.  Code Field doesn't implement that method, so it ends up calling the parent `Field` method:

```php
    /**
     * @inheritdoc
     */
    public function getStaticHtml(mixed $value, ElementInterface $element): string
    {
        // Just return the input HTML with disabled inputs by default
        Craft::$app->getView()->startJsBuffer();
        $inputHtml = $this->getInputHtml($value, $element);
        $inputHtml = preg_replace('/<(?:input|textarea|select)\s[^>]*/i', '$0 disabled', $inputHtml);
        Craft::$app->getView()->clearJsBuffer();

        return $inputHtml;
    }
```

...which explicitly removes any queue'd JavaScript from rendering, which then causes the Monaco editor to not be instantiated, so the formatting is never applied.

Instead, we now implement our own `::getStaticHtml()` which renders the Monaco editor as `readOnly` so things display as intended.

Addressed in: https://github.com/nystudio107/craft-code-field/commit/cbae5010f30ebc082353b32fca110322e7356e26 & https://github.com/nystudio107/craft-code-field/commit/cdcfda0fad7ebfca15a51f0e98051ad474d608d1

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-code-field": "dev-develop-v3 as 3.0.11”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-code-field": "dev-develop-v4 as 4.0.11”,
```
Then do a `composer clear-cache && composer update`

**Closed as completed by khalwat** 2023-10-05 12:11 UTC
Labels: bug

**Comment by gbowne-quickbase** [comment] 2023-10-05 13:36
Thanks for a quick fix, and glad it was "interesting" at least. 
P.S. I'm doing your pushups for you in October

**Comment by khalwat** [comment] 2023-10-05 21:26
How many you doing?

**Comment by gbowne-quickbase** [comment] 2023-10-06 12:37
I’m following the pattern of Month+Day so today is 10+6. It’s a good challenge!

**Comment by khalwat** [comment] 2023-10-08 16:26
ooooh sweet! You should carry the torch for me, and finish the entire year out! 💪
